spring:
  profiles:
    active: local

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:database
  jwt:
    secret: iwantcoffee-americano+ice-americano-is-best-i.love_it+yaho
    expirationMinute: 15
payment:
  secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
