# .github/workflows/deployDev.yml
name: Deploy-Dev (self-hosted)

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, Linux, ARM64 ] # ★ matrix가 필요 없으므로 runner를 직접 지정합니다.
    steps:
      - name: Run deploy
        run: |
          BRANCH_OVERRIDE="${{ github.ref_name }}" bash ~/deploy.sh
