# .github/workflows/deploy.yml
name: Deploy (self-hosted)

on:
  push:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - branch: main
            runner: [ self-hosted, Linux, ARM64 ]
          - branch: develop
            runner: [ self-hosted, Linux, ARM64 ]
    steps:
      - name: Run deploy
        # if 조건문을 스텝 내부에 위치시켜 matrix 변수를 참조
        if: github.ref_name == matrix.branch
        run: |
          BRANCH_OVERRIDE="${{ github.ref_name }}" bash ~/deploy.sh
